# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Fiji Exercises Collection
author: Image Analysis Collaboratory @ Harvard Medical School
copyright: "2025"
logo: logo/iac_logo_white.png

exclude_patterns: [_build, .DS_Store, "**.ipynb_checkpoints", README.md, _internal/**, build_book.sh]

# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: cache

# Information about where the book exists on the web
repository:
  url: https://github.com/HMS-IAC/fiji-exercises-collection/  # Online location of your book
  branch: main  # Which branch of the repository should be used when creating links (optional)

html:
  use_repository_button: true
  extra_footer: |
      <p>
      All content is licensed under <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank">CC-BY 4.0</a>, except where noted otherwise.
      </p>

# Define the name of the latex output file for PDF builds
latex:
  latex_engine: xelatex
