# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Fiji Exercises Collection
author: Image Analysis Collaboratory, Harvard Medical School, Boston, MA, USA - https://iac.hms.harvard.edu
copyright: "2025"
logo: logo/iac_logo_white.png

exclude_patterns: [_build, .DS_Store, "**.ipynb_checkpoints"]

# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

html:
  extra_footer: |
      <p>
      All content is licensed under <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank">CC-BY 4.0</a>, except where noted otherwise.
      </p>


# Information about where the book exists on the web
# repository:
#   url: https://github.com/executablebooks/jupyter-book  # Online location of your book
#   path_to_book: docs  # Optional path to your book, relative to the repository root
#   branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
# html:
#   use_issues_button: true
#   use_repository_button: true